config/routes.rb
Rails.application.routes.draw do

  root 'bugs#new', as: '/'

  scope(path_names: { new: 'nowy', edit: 'edycja'}) do
    resources :bugs, path: 'robaczki'
  end

end

app/models/bug.rb
class Bug < ActiveRecord::Base
  validates :description, presence: true,
                          length: {minimum: 10}
  validates :url, presence: true,
                  length: {minimum: 5}
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bugs_controller.rb
class BugsController < ApplicationController
  def index
    # @bugs = Bug.all
    @bugs = Bug.last(5)
  end

  def show
    @bug = Bug.find(params[:id])
  end

  def new
    @bugs = Bug.last(5)
    @bug = Bug.new
  end

  def create
    @bug = Bug.new(bug_params)

    if @bug.save
      flash[:success] = "Bug #{@bug.id} został utworzony!\nDziękujemy za zgłoszenie :)"
      redirect_to new_bug_path
    else
      flash[:error] = "Coś nie halo. Popraw podświetlone pola."
      render :new
    end
  end

  def edit
    @bug = Bug.find(params[:id])
  end

  def update
    @bug = Bug.find(params[:id])

    if @bug.update_attributes(bug_params)
      flash[:success] = "Edycja zakończona powodzeniem."
      redirect_to new_bug_path
    else
      flash[:error] = "Coś poszło nie tak. Spróbuj ponownie."
      render :edit
    end
  end

  def destroy
    @bug = Bug.find(params[:id]).destroy
    redirect_to bugs_path
    flash[:notice] = "Bug #{@bug.id} został usunięty!"
  end

  private

    def bug_params
      params.require(:bug).permit(:description, :url)
    end 

end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type.to_sym] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} alert-dismissible", role: 'alert') do
        concat(content_tag(:button, class: 'close', data: { dismiss: 'alert' }) do
          concat content_tag(:span, '&times;'.html_safe, 'aria-hidden' => true)
          concat content_tag(:span, 'Close', class: 'sr-only')
        end)
        concat message
      end)
    end
    nil
  end
end

app/helpers/bugs_helper.rb
module BugsHelper
end

app/views/bugs/_form.html.erb
<section class="form-group">
	<%= form.label :description, 'Opis błędu' %>
	<%= form.text_area :description, class: "form-control" %>
</section>
<section class="form-group">
	<%= form.label :url, 'URL' %>
	<%= form.text_field :url, class: "form-control" %>
</section>

app/views/bugs/edit.html.erb
<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<div class="row">
			<h1><span class="text-success"><i class="fa fa-bug"></i></span> Edycja BUGa nr: #<%= @bug.id.to_s %></h1>
			<p><%= link_to 'Wróć do listy', new_bug_path %></p>
		</div>
		<div class="row">
			<%= form_for(@bug, html: {class: "form"}) do |form| %>
				<%# render(partial: 'form', locals: {form: 'form'}) %>
				<section class="form-group">
					<%= form.label :description, 'Opis błędu' %>
					<%= form.text_area :description, class: "form-control" %>
				</section>
				<section class="form-group">
					<%= form.label :url, 'URL' %>
					<%= form.text_field :url, class: "form-control" %>
				</section>
				<%= form.submit 'Zapisz zmiany', class: 'btn btn-default' %>
			<% end %>
		</div>
	</div>
</div>

app/views/bugs/index.html.erb
<div class="row">
	<h1>Bugtracker Homepage</h1>
</div>

	<% if @bugs.empty? %>
		<div class="row">
			<div class="alert alert-success" role="alert">
				<h2>Brawo! Nie ma żadnych bugów!</h2>
			</div>
		</div>
	<% end %>

<div class="row">
	<p><%= link_to 'Zgłoś nowy bug', new_bug_path, class: "btn btn-danger btn-sm" %></p>
</div>

<div class="row">
	<table class="table table-hover">
		<tr>
			<th width="5%"><i>#</i></th>
			<th width="50%">Opis</th>
			<th width="30%">URL</th>
			<th width="15%">Akcje</th>
		</tr>

		<% @bugs.each do |bug| %>
			<tr>
				<td><span class="text-danger"><i class="fa fa-bug" title="To jest bug"></i></span></td>
				<td><%= link_to bug.description, bug_path(bug) %></td>
				<td><%= bug.url %></td>
				<td>
					<div class="btn-group btn-group-xs" role="group"> 
						<%= link_to 'Usuń', bug_path(bug), method: :delete, data: {confirm: "Sure?!"}, class: "btn btn-danger" %>
						<%= link_to 'Edytuj', edit_bug_path(bug), class: "btn btn-info" %>
						<%= link_to 'Usuń', bug_path(bug), method: :delete, data: {confirm: "Sure?!"}, class: "btn btn-success" %>
					</div>
				</td>
			</tr>
		<% end %>
	</table>
</div>

app/views/bugs/new.html.erb
<div class="row">
	<h1>Bugtracker Homepage</h1>
</div>
<% if @bugs.empty? %>
	<div class="row">
		<div class="alert alert-success" role="alert">
			<h2>Brawo! Nie ma żadnych bugów!</h2>
		</div>
	</div>
<% end %>
<div class="row">
	<table class="table table-hover">
		<tr>
			<th width="5%"><i>#</i></th>
			<th width="50%">Opis</th>
			<th width="30%">URL</th>
			<th width="15%">Akcje</th>
		</tr>

		<% @bugs.each do |bug| %>
			<tr>
				<td><span class="text-danger"><i class="fa fa-bug" title="To jest bug"></i></span></td>
				<td><%= link_to bug.description, bug_path(bug) %></td>
				<td><%= bug.url %></td>
				<td>
					<div class="btn-group btn-group-xs" role="group"> 
						<%= link_to 'Usuń', bug_path(bug), method: :delete, data: {confirm: "Klikając Usuń błąd w kodzie nie zniknie.\nChcesz kontynuować?!"}, class: "btn btn-danger" %>
						<%= link_to 'Edytuj', edit_bug_path(bug), class: "btn btn-info" %>
						<%# link_to 'Usuń', bug_path(bug), method: :delete, data: {confirm: "Sure?!"}, class: "btn btn-success" %>
					</div>
				</td>
			</tr>
		<% end %>
	</table>
	<hr>
</div>
<div class="row">
	<div class="col-md-8">
		<div class="row">
			<h3>Zgłoś nowy BUG</h3>
			<hr>
			<!-- <p><%# link_to 'Wróć do listy', bugs_path %></p> -->
		</div>
		<div class="row">
			<%= form_for(@bug, html: {class: "form"}) do |form| %>
				<section class="form-group">
					<%= form.label :description, 'Opis błędu' %>
					<%= form.text_area :description, class: "form-control" %>
				</section>
				<section class="form-group">
					<%= form.label :url, 'URL' %>
					<%= form.text_field :url, class: "form-control" %>
				</section>
				<%= form.submit 'Zgłoś błąd', class: "btn btn-default" %>
			<% end %>
		</div>
	
	</div>
</div>

app/views/bugs/show.html.erb
<div class="row">
	<div class="center-block">
		<h1><span class="text-success"><i class="fa fa-bug"></i></span> Szczegóły błędu nr: #<%= @bug.id %></h1>
		<p class="text-muted small">
			Zgłoszono <%= @bug.created_at.strftime("%d %b %Y") %> o godzinie <%= @bug.created_at.strftime("%H:%M") %>
		</p>
		<%= @bug.description %> - <span><%= @bug.url %></span>
		
		<p><%= link_to 'Wróć do listy', new_bug_path %></p>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bugtracker</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'bugs' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container">
		<div class="col-md-10 col-md-offset-1">
		
			<div class="row"><%= flash_messages %></div>

			<%= yield %>

		</div>
	</div>
</body>
</html>